# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32d65baa080f8c49184f72e5bbe40f142a07a0d99984208e9fe54dbad5e68a9381d278d6426c483f44982a5506458268e88688d729f34091e4d2f6d6003922bd

test:
  secret_key_base: 1af8f340ae7e50532a77fbe43019713abf4a36d7dda7d43078eb27ea732ef4533ac2ede4ac93b56f69362f95ddda6bc0e066f6fde3448d82e56d7c068a6ff1c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
